### ISSUE TITLE
Comments loads full page in iframe on login

### ISSUE THREAD

**Issue by adamoxford** [vanilla/wordpress-vanilla#14]
This may be an issue with Vanilla core rather than the WP plugin, but a bug has appeared in the embedded comments system for us. Possibly a result of server upgrade?:
- Expected (previous) behaviour: When a user logs in to comment under a WP post, the redirect reloads the comment iFrame from the forum embed url. 
- Current behaviour: The iFrame is refreshing on login, but results in the full parent page loading (not just the comments). If approved domains are not listed in the Vanilla control panel, the forum homepage loads.
- If the page is refreshed, loads with Wordpress article and logged in Vanilla comment field correctly.

You can see current behaviour here: htxt.co.za

Suggested solution is to force a full page refresh on pop-up close?

More details here: https://vanillaforums.org/discussion/32442/comments-login-loading-full-page-not-embed#latest

**Comment by linc** [comment]
Disable the login popup under your advanced embed settings in the Dashboard.
