### ISSUE TITLE
Handle categoryTree in embed and widgets

### ISSUE THREAD

**Issue by DaazKu** [vanilla/wordpress-vanilla#17]
https://github.com/vanilla/wordpress-vanilla/blob/master/embed.php#L141
https://github.com/vanilla/wordpress-vanilla/blob/master/widgets.php#L114

It can be categories or categoryTree. The latter needs to be flattened!

**Comment by rosswintle** [comment]
This is marvellous. Thank you. Any chance this will ever make it into a new, Vanilla-2.5 compatible release of the plugin?  See https://open.vanillaforums.com/discussion/36207/wordpress-plugin-update-for-vanilla-2-5
