### ISSUE TITLE
Problem with WP Plugin Vanilla Forums Version 1.1.18

### ISSUE THREAD

**Issue by helpli-fa** [vanilla/wordpress-vanilla#27]
i have changed the url of website from http to https and some days after i have seen, that i can update to the 1.1.18 version. during the update i receive a fatal error with the information:

Parse error: syntax error, unexpected '[' in /web/htdocs/www.url-of-the-website/home/wp-content/plugins/vanilla-forums/functions.php on line 480

what can i do?

**Comment by DaazKu** [comment]
I assume that your php version is lower than PHP 5.4.0?

If that's the case you will have to upgrade to a more recent version of PHP.

**Comment by DaazKu** [comment]
Alternatively you could go in that file and replace `$result = [];` by `$result = array();` on line 480 and hope that it is the only occurence of the short array syntax there is in the code.

[Anything below PHP 7.1 will be a security risk in 2019](http://php.net/supported-versions.php).

**Comment by helpli-fa** [comment]
thank you for your time. works :)
