### ISSUE TITLE
Use get_avatar_url instead of get_avatar + SimpleXMLElement

### ISSUE THREAD

**Issue by x00** [vanilla/wordpress-vanilla#5]
Why do you use this fudge (your own words)?

https://github.com/vanilla/wordpress-vanilla/blob/master/functions.php#L354-L359

**Comment by tburry** [comment]
The get_avatar_url() function was added in Wordpress 4.2. We wrote the plugin way before that.

**Comment by x00** [comment]
ok but xml parsing is a bit overkill. 

something like `preg_match('/src="([^"]+)"/', $img, $match);` would do. 

xml parsing  did cause a bug with vanilla user, it is expected a closing slash or something.
