### ISSUE TITLE
Fix Forum Widgets - Wordpress Plugin

### ISSUE THREAD

**Issue by JosephFleming** [vanilla/wordpress-vanilla#7]
Add forum widgets to your blog: Place widgets throughout your blog with information like: recent discussions, discussion categories, and recent forum activity.

Widgets will not display information.

**Comment by MikhailRoot** [comment]
check my Pull requests https://github.com/vanilla/wordpress-vanilla/pulls i've updated REST routes so widgets should work ok.
UPD: Now they are merged so just update your plugin  from main repo.

**Comment by JosephFleming** [comment]
Thanks,

Mikhail your a champ!

P.S. about to praise you in our team chat :p

Joe

On Wed, Mar 23, 2016 at 12:00 PM, Mikhail <notifications@github.com> wrote:

> check my Pull requests https://github.com/vanilla/wordpress-vanilla/pulls
> i've updated REST routes so widgets should work ok.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/vanilla/wordpress-vanilla/issues/7#issuecomment-200411441>
>



-- 

<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2BpySRW65jv6b3N1DxYW7fRL1x56dM6vf4MgCbn02?t=http%3A%2F%2Fvanillaforums.com%2F&si=5251557416763392&pi=02ed0da1-3342-44c4-8935-7744217553aa>

Joseph Fleming

Vanilla Forums

*T: 1.866.845.0815x105*

vanillaforums.com

Check us out on:Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2BpySRW65jv6b3N1DxYW7fRL1x56dM6vf4MgCbn02?t=https%3A%2F%2Ftwitter.com%2Fvanilla&si=5251557416763392&pi=02ed0da1-3342-44c4-8935-7744217553aa>
  Facebook <https://www.facebook.com/vanillaforums> Google+
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2BpySRW65jv6b3N1DxYW7fRL1x56dM6vf4MgCbn02?t=https%3A%2F%2Fplus.google.com%2Fb%2F114911737178548458245%2F114911737178548458245&si=5251557416763392&pi=02ed0da1-3342-44c4-8935-7744217553aa>
 LinkedIn
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2BpySRW65jv6b3N1DxYW7fRL1x56dM6vf4MgCbn02?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fvanilla-forums-inc&si=5251557416763392&pi=02ed0da1-3342-44c4-8935-7744217553aa>

**Comment by JosephFleming** [comment]
Our new e-book shows helps you uncover how you can transform your customer service experience in the digital age.

Vanilla Forums (http://vanillaforums.com?utm_campaign=Guides&utm_source=hs_email&utm_medium=email&utm_content=28675663&_hsenc=p2ANqtz-_5FXY4nFggD-3NJs_kNmfbSj7xOGxpYbh6PrAxNbtubwCzbX6nRWf_KykkEeoJpDISyj6lor8H6hepbam5SJry80iqKirTkQ4RxCciEV8W08vtD7PwiJQtpw-Sf_Oreg0cnflBL4xDStcG3RNW2lsC4h-RezJ5sbgVhVPQ0Yiwn_gxav7Tol72ed403He_w3gtYmfy4-x5YBsK1GSecDRE-w-C-A&_hsmi=28675663)

Hello vanilla/wordpress-vanilla

It can be easy for customer service departments to continue doing what they've always done.

However, today's consumer have many options in terms of how they connect with a company for customer support issues. Your company has to be where the customer is.

Based on feedback from our customers, product experts, and service industry thought leaders, we've pulled together best practices and compiled them into one handy (and free) ebook, that would help you understand how customer service is being affected by the new digital transformation.

Transforming_the_Digital_Customer_Support_Experience.png (http://pages.vanillaforums.com/transforming-digital-customer-service?utm_campaign=Guides&utm_source=hs_email&utm_medium=email&utm_content=28675663&_hsenc=p2ANqtz--HqCDOpPxaVXtLBNRU-ewIcs2gBukFCjVtdrAdaeRSn9i4I_hUvhUT8chuRzTekSyAQ78PmkRvFIUfaMkeC5DoAfjH3nk7jBV5cFxuJW2tvoZM4dJTo3ELpsXTciYQKULexUt3c_qdQyqcFnsgteecP--MLEXkjhbXTe8o_P5UyOfBFQgi5Cos56mBtTICHZdPB7CZieBDSAiaK1z8hwX7mPRUxw&_hsmi=28675663)

hubspot-cta-button-download.png (http://pages.vanillaforums.com/transforming-digital-customer-service?utm_campaign=Guides&utm_source=hs_email&utm_medium=email&utm_content=28675663&_hsenc=p2ANqtz-_h-bwI8gNIicXD8pK4pWsanXSbqA4y_GpgzATgsqYWrCP0zxOJ5hs5UscseIHjMKP8fs_pg8_CLdqIhyF2_Qn_4hL38vDBrhfn6JTKr9OLuk_XtRluCIVEkiWzDBHEan0YgEO1cev5HVAebI17OcpYddyo8o84490xsjb3MD0mzKa1Db5T_P3Dh_A16QafddApi442hcWSVcm7YVM5aI_VIqY-Pw&_hsmi=28675663)

Get your copy here (http://pages.vanillaforums.com/transforming-digital-customer-service?utm_campaign=Guides&utm_source=hs_email&utm_medium=email&utm_content=28675663&_hsenc=p2ANqtz--pphF1biNpNEm6g8Ux-fXlvsBaTFmAR6-FJQgVY_gGp2opzVPgRIvj5xk6jmMVsKbDhFaHhdUgwzwm1phf6BXQcr1EkqOcejvpmc5TqYDuvocoELbC7RawriWZR-HTBmuk4fUPdCjx5iLYDCxWw6UGSCP6airMAdcAOTN32-27_M4ioi_zKdC_-ZTGw7bw9onufUPAlSQLJ7H4z1Vv2U8qaGCIVg&_hsmi=28675663) and learn how the new customer service organization can move with the times.

adrianpic2.jpg Adrian Speyet
Marketing Manager
adrian@vanillaforums.com (mailto:adrian@vanillaforums.com)
Vanilla Forums

Check us out on: Twitter (https://twitter.com/vanilla?utm_campaign=Guides&utm_source=hs_email&utm_medium=email&utm_content=28675663&_hsenc=p2ANqtz-8yIZF89GtUpG2GoEkk6c7b_LR_BbO9IKmPo2aB9tGD1xqsGWtex6Z3jSjQpbQIdIE91DnVdzk5qvP7G3-PdnsOGm_v4DOAMGsWMIzUOEHe0AL_TQKcDjtzZMNCQ9PeiNNY72xfhI7iRE7ERYzzkE-YZvLk4Q6p63jqp9XoV5bSwSrRieklYGx81DfsFyDHAX3x3Mqg1j1UjE6UAiAILImgMCHeUA&_hsmi=28675663)   Facebook (https://www.facebook.com/vanillaforums?utm_campaign=Guides&utm_source=hs_email&utm_medium=email&utm_content=28675663&_hsenc=p2ANqtz-_FZQAdECO8UgYC9y9D7gQzNrA5ZeXOkD7CP3OogqonC2RhWHNTZXaZspax4SttemhERnZgTMqgw3U-QMxUIsNkBRepOD-beLbAYJPk-nFLp61ZVWJrTogB7GDulWFtJcG1E-BUEOacNg6Jqmm26do3EhlTTNTtUtOxi2YXSaxGtm2qixdHSRDZV6yr_1OA3svYgTTWMN6OShe7mI6gwmWnthApRQ&_hsmi=28675663)  Google+ (https://plus.google.com/b/114911737178548458245/114911737178548458245?utm_campaign=Guides&utm_source=hs_email&utm_medium=email&utm_content=28675663&_hsenc=p2ANqtz-9rTDpHbOwLmKB_qRQWkNmLr8-PKUyUdCk2nnyHt_1AZpoCwi3dyzZGctIxTN88nF_HV7tbxmJhwtWwz5xHBDdIBItjutSMqiktvcG5YsOBLwHcjyMNgbFh0Rn9GtaVJThumrfTn3-71WvTT96CXI7MLajkcoOjTF65VziPCSrhihbWRd91qMKxLf5s0O5s8m8ncR9bu1uptXIfL46j3h4hAIwXOA&_hsmi=28675663)  LinkedIn (http://www.linkedin.com/company/vanilla-forums-inc?utm_campaign=Guides&utm_source=hs_email&utm_medium=email&utm_content=28675663&_hsenc=p2ANqtz--PId2CadmMfFS--in6zSrCCcKeN4KZK5ACLKWdO1MfYjHjW-7FIBiLKunR_nYGfYGNT0Z7nCteA01XiuWpqr0xo27ibLH-zLkJiDe2AElf6JC_4p3j2Jh1u5-N6tKNZnD5-zsr111Im6jjK601iunC1fxKlX29dtO4cDi-vc8B2UoC8VoMXHAMFWn679eEjgXhhKDfLRFadtBqr9AJK6vzNisuxQ&_hsmi=28675663)

Vanilla Forums Inc.
388 St-Jacques
#800
Montreal,
QC
H2Y 1S1
Canada

You received this email because you are subscribed to Whitepaper from Vanilla Forums Inc. .

Update your email preferences (http://95135.hs-sites.com/hs/manage-preferences/unsubscribe?v=1&d=eyJlYSI6InJlcGx5KzAwYmY3MzRhN2YzN2UwMWI0MzBlMzZlZWFjZDNmY2E4NjEzN2IyNDNkZDc1MThiODkyY2YwMDAwMDAwMTEzMGE3Zjk0OTJhMTY5Y2UwNjZkMWM3ZUByZXBseS5naXRodWIuY29tIiwiZWMiOjI4Njc1NjYzLCJzdWJzY3JpcHRpb25JZCI6MjEwMjMwLCJldCI6MTQ2MTE2Njg4MTI0MywiZXUiOiI1NjZmN2MxMi0zZDZiLTRiMmUtYmQxNC1hNTgyOTA3MTRjZWEifQ%3D%3D&utm_campaign=Guides&utm_source=hs_email&utm_medium=email&utm_content=28675663&_hsenc=p2ANqtz-_LyevQez6F_OmdmoWSmuTbiGj0GXkVaJkIcQKAJKa8pt7_jKuzJ5-1cFJe_049rOk3XLAXJsIsS_54QGhMIeAQWU9ZAx4g_npXIt5tYrLKH3sVc3d0QPPiqK6YhGxJX0sZzoMrnh9Ydn0TKRZQ6ok_KXSyVm4QvwVA3ibmXqg52KOEdwRSwK70QsV8bPXl0WSkyVxc0F4ZccaiPVXhQD91q8XBcw&_hsmi=28675663) to choose the types of emails you receive.

Unsubscribe from all future emails (http://95135.hs-sites.com/hs/manage-preferences/unsubscribe-all?v=1&d=eyJlYSI6InJlcGx5KzAwYmY3MzRhN2YzN2UwMWI0MzBlMzZlZWFjZDNmY2E4NjEzN2IyNDNkZDc1MThiODkyY2YwMDAwMDAwMTEzMGE3Zjk0OTJhMTY5Y2UwNjZkMWM3ZUByZXBseS5naXRodWIuY29tIiwiZWMiOjI4Njc1NjYzLCJzdWJzY3JpcHRpb25JZCI6MjEwMjMwLCJldCI6MTQ2MTE2Njg4MTI0MywiZXUiOiI1NjZmN2MxMi0zZDZiLTRiMmUtYmQxNC1hNTgyOTA3MTRjZWEifQ%3D%3D&utm_campaign=Guides&utm_source=hs_email&utm_medium=email&utm_content=28675663&_hsenc=p2ANqtz-8qzmCWQ_fRHGIY8G5Pv4TpCtg9P2bzt44JDYKGrXFDovfUBr2SbaOik9PbpMpGUSSYxdDZllM3q0GrlWNq7KFn22oVGfiMq2U9cC0X0ko-IDSjxkrZDMgQmZt8o920CCmFuPW-Ixk5EULRfJlTnp26fRqRZRa6aGrPwcZ_zL3TJgYurcE4ZsfAFvAlq9a0WsxmNOggkG1C-8d78iJ2SGfxbGHzUA&_hsmi=28675663)

**Comment by JosephFleming** [comment]
Join us for our next webinar featuring Feverbee's Richard Millington in this 60 min session on how to drive member engagement & behavior change through decision design on May 25th @ 1pm EDT. Register now!

Vanilla Forums (http://vanillaforums.com?utm_campaign=Feverbee+and+Vanilla&utm_source=hs_email&utm_medium=email&utm_content=29083443&_hsenc=p2ANqtz--L9dO5GnIdkz9QREKweQmyAnUH8XdIzaqBz5fBHsB9Y2RJwJpLVbxU5YpUIhFXtH_ETUY-41hy7mCugKUsc_Q4juzZE0xnKW6z6yjoUUp0xQV0tf3XNpjrIVq6QlHIgeEIvqoT02J5R48gNm1zra2Cc5EcilXDhEHz0YcMbf_Qv3qC68OZHNKbhVXBSGYntkJi3nLiL1JV2tXITMdEJofr5r5b7A&_hsmi=29083443)

Hello vanilla/wordpress-vanilla

I’m sure you’ve faced the challenge in ways to help you engage members and maximize lifetime value throughout the entire customer lifecycle.

The good news is that you are in control of customer engagement. Richard Millington, respected author and community management expert, will walk you through the best practices to increase user engagement and drive behavior change.

FeverBee_Social_Ads_Linkedin_1200x627_1.png (http://pages.vanillaforums.com/feverbee-vanilla-webinar?utm_campaign=Feverbee+and+Vanilla&utm_source=hs_email&utm_medium=email&utm_content=29083443&_hsenc=p2ANqtz-8QoDJH1Fvk6J6QKJ06N3reHoh95bpPJJOPUmz3NEws5fvIPgkqMfMxzolPK00KswRbEQpqZ-bT9f60G31queuWZNm7DDGHGze30EP3f6hL2apasRldGlnIQBfpU-cagYAlGBDz87APb9UtFjJAlskX43z33Xu0SCPRJQPVWJ-q0I05Lz5kFlsJt_UOWhvUKLCLGWS7E08InBXaasBAIsBMW01H9A&_hsmi=29083443)

Learn how user engagement needs to be a part of your community strategy from day one and continue to be a focus. Find out the tactics that keep your audience coming back for more and help lurkers become engaged community members.

RSVP your spot NOW, spaces are limited! (http://pages.vanillaforums.com/feverbee-vanilla-webinar?utm_campaign=Feverbee+and+Vanilla&utm_source=hs_email&utm_medium=email&utm_content=29083443&_hsenc=p2ANqtz-8Xr8m6_X8pujKI-G0BvlyoytGQkUskGnsKJnXPtNBLH-9nApFdxNU-rbnAJSCC_dxYB_urta3nbwyHYgtDGz_a9S3hTjfqHsinzbpMIel-J8FDVRSgRNlzKt_8zVa81Q09jrGdwMq3E9NZ6M4SSSkGeLHcsYumAwDjxHK-1ET5-IwexJVW_RPBjOo8aDJ4Q-pZDnTqVvKPjf9UEjc55uIjU5DuWA&_hsmi=29083443)

adrianpic2.jpg Adrian Speyet
Marketing Manager
adrian@vanillaforums.com (mailto:adrian@vanillaforums.com)
Vanilla Forums

Check us out on: Twitter (https://twitter.com/vanilla?utm_campaign=Feverbee+and+Vanilla&utm_source=hs_email&utm_medium=email&utm_content=29083443&_hsenc=p2ANqtz-_086BpxXsCykJa3t-KFwoNz8qTqa5QFp8ku2MDjHJumQ5AwgPMcL6q8g9bhQSRvMu1L-LNVh_NkqnkjmQU6MjH8nsyadILetkjcZhnAz2AW1bZOkXwF_8y2oQ7EpB3_v5Veld1IBYE_YGIQOZcPp2oI2gBIW1a_xYWbRxnyZA3gmg2nnL8DlXCRbjQE-jsMiW2S6U_t9VVHgAs9WPTkdheWGLULg&_hsmi=29083443)   Facebook (https://www.facebook.com/vanillaforums?utm_campaign=Feverbee+and+Vanilla&utm_source=hs_email&utm_medium=email&utm_content=29083443&_hsenc=p2ANqtz--kS31lAjY_aXCrAUf7LfoBev7KNY-eOow01YZblQkBWp4nNnLK0AaCYx_GaAcn34U4hqUVYFvPRxhm5ZWckQuOmnFklMo-hyQwwYRyI5r7eqpb1NSW146D7tsHEMuakMU0o__S2hoKCmw9PJ9nQeqFwFKhmi656SjnIWppzHjy2-UgXbGM8u-hNPturTyd2SqMQzXeKG_4s3EAEcV_npGIgfOzDg&_hsmi=29083443)  Google+ (https://plus.google.com/b/114911737178548458245/114911737178548458245?utm_campaign=Feverbee+and+Vanilla&utm_source=hs_email&utm_medium=email&utm_content=29083443&_hsenc=p2ANqtz-9OiJkFwuKVMfVFCRtxtKzJGyp2D1ZdxHVHrmfsE80GBgjVVzRtBh0ke3eAlQrpw8WZL_TaQdE3BFbGGFCxz9iOEHd0Sv_3z4SXloA9jL5LD2AKNgDd6g303hPumIk5hsjG0s-TMHx4QiksOiWzzkYiNtjVSna-TBGWD2VpkidMbUIYFsMp3kdGtTOXqSNRVt-VJhJSUfujZttYf1hRKdsnF-9qeg&_hsmi=29083443)  LinkedIn (http://www.linkedin.com/company/vanilla-forums-inc?utm_campaign=Feverbee+and+Vanilla&utm_source=hs_email&utm_medium=email&utm_content=29083443&_hsenc=p2ANqtz-8B01FUQ3fBUjUOzrtBTredOWWeGZR4nArQQV7UR3gp6zzBp1oKhXz8pWrbwlTiBfJ7T4cwGa793boZx8qUnrI-OLmWcEETJnqfXHOmts0w3Ur6GafhEhlj8j4CBKjrVD4fvhp8YG5g8S-M0p8YCURZqX-UvKLrvSWoxO92AWOR1E9MUgbtDMFoemf0lONq0KgwBP0DlZY2zH3tDHKxO_mR1jBQJg&_hsmi=29083443)

Share on Facebook (http://www.facebook.com/share.php?u=http%3A%2F%2F95135.hs-sites.com%2F-temporary-slug-6375de3f-d174-4c40-9ae9-f779dfbdfbc6%3Futm_medium%3Dsocial%26utm_source%3Dfacebook&utm_campaign=Feverbee+and+Vanilla&utm_source=hs_email&utm_medium=email&utm_content=29083443&_hsenc=p2ANqtz-8ny2RN8COFBpbAsE5tEJal3dIWyzypvsW3Ju-kDI5870uT6U2QcQcS5g9wk-g3XNYorNqvHy0Jly80uRjODPSbnRNVrCdGJLDWCiY64mO85KGuBGfgSfDIEny5vtToaowh3lxBrjiJhaqJb6JiMSyAKo2WzgelPtSzg3pAdBmrwfcTyk9Bez4Jju9bnpBdmxjeQ34YATCSPBmS7FSbBx2dnAusGg&_hsmi=29083443)  Share on LinkedIn (http://www.linkedin.com/shareArticle?mini=true&url=http%3A%2F%2F95135.hs-sites.com%2F-temporary-slug-6375de3f-d174-4c40-9ae9-f779dfbdfbc6%3Futm_medium%3Dsocial%26utm_source%3Dlinkedin&utm_campaign=Feverbee+and+Vanilla&utm_source=hs_email&utm_medium=email&utm_content=29083443&_hsenc=p2ANqtz--s0rWY50jg6ZkxUkze5EbrFwWqVtrqi71DPUSdA8mrfzXxz6s6nSuvv1pzume3vlb7L6WR_JOc4y4_PwzD2UDRU3UbF5ZA2H5dyN-7iq-5obYHgRdEzKCbSOsm1GfFYopCQBnozgwNYEjYx20A-KA1lvVlvUVtvL_E6BDEyVMpGPIKbqMkm2eo0W3dTW9cGQxTyjP7VaNsZ-vFZosCVpXwDwVZlA&_hsmi=29083443)  Share on Twitter (https://twitter.com/intent/tweet?original_referer=http%3A%2F%2F95135.hs-sites.com%2F-temporary-slug-6375de3f-d174-4c40-9ae9-f779dfbdfbc6%3Futm_medium%3Dsocial%26utm_source%3Dtwitter&url=http%3A%2F%2F95135.hs-sites.com%2F-temporary-slug-6375de3f-d174-4c40-9ae9-f779dfbdfbc6%3Futm_medium%3Dsocial%26utm_source%3Dtwitter&source=tweetbutton&text=%5BNew%20Webinar%5D%20How%20to%20Drive%20Community%20Engagement%20%26amp%3B%20Behavior%20Change&utm_campaign=Feverbee+and+Vanilla&utm_source=hs_email&utm_medium=email&utm_content=29083443&_hsenc=p2ANqtz-_GZzIcRqp71fo-csqsO6-eL0pckkmr8df-1XkwtxobZMhlJ-xuKSCuJE7OuJ2vBDn30Ezqt9L4OC35BwYpylQlhLWWPRpElXp_WCJ0T_kF2D_usa-XCvBm2mlYyI1A4zKvb2tR5WWU1Cz_20c7j9os29CB0RrQmhUeIoVnGu0No4RgdctybCohLVeBgh1h1PXEmURys2f5ZT4h3wSF39-6Kmf3zg&_hsmi=29083443)  Share on Google+ (https://plus.google.com/share?url=http%3A%2F%2F95135.hs-sites.com%2F-temporary-slug-6375de3f-d174-4c40-9ae9-f779dfbdfbc6%3Futm_medium%3Dsocial%26utm_source%3Dgoogle_plus&utm_campaign=Feverbee+and+Vanilla&utm_source=hs_email&utm_medium=email&utm_content=29083443&_hsenc=p2ANqtz-8Ct71kjEcalIRP1mfHMs8waStLbrprIIXEoBapvYRkpT-RJIWVw5owOipuxS4xrjjNUFCDFCMJUiAxGix09gb7DB6pUkWBoRMrmsHMdyQiUdIm_hCRiUcZDT0QgL_S7jcF9vEJyKEXomQm8Dl0E2-sQBthwAvQ3EQlxV8WnHyVr0Tp1OGzn7U0m9qUsb-DUK1OU2Hw2oWU5Ya4DLi1FOe3Low6tg&_hsmi=29083443)

Vanilla Forums Inc.
388 St-Jacques
#800
Montreal,
QC
H2Y 1S1
Canada

You received this email because you are subscribed to Webinar from Vanilla Forums Inc. .

Update your email preferences (http://95135.hs-sites.com/hs/manage-preferences/unsubscribe?v=1&d=eyJlYSI6InJlcGx5KzAwYmY3MzRhN2YzN2UwMWI0MzBlMzZlZWFjZDNmY2E4NjEzN2IyNDNkZDc1MThiODkyY2YwMDAwMDAwMTEzMGE3Zjk0OTJhMTY5Y2UwNjZkMWM3ZUByZXBseS5naXRodWIuY29tIiwiZWMiOjI5MDgzNDQzLCJzdWJzY3JpcHRpb25JZCI6MjEwOTk5LCJldCI6MTQ2MjIwNzAxNjk0NSwiZXUiOiJjMzc5MWYxMC1kMWJlLTQ4NWYtOTFiOC1lNzZmMDRhODk1MTQifQ%3D%3D&utm_campaign=Feverbee+and+Vanilla&utm_source=hs_email&utm_medium=email&utm_content=29083443&_hsenc=p2ANqtz--gtW9TUzHd_6PcH8Arze_nucIQ5AiiyZGuo_rIn4HAjXsiTTHPHMOrNDWLCULQ4qhZ6aSpRmPiieyyzf9OsVRrdQ-wACcZfL2jzc7H9CoKCmgILl-hBgoE62S_FKUI__xVrlJGmLPa6CkR05nyFdv9N8la9Ei3kIAj4vhCMDqyA7lBouEFHQIYM95wgavCMkWCcj4eOI3bLc2gg_Tl_HA5Y34L1A&_hsmi=29083443) to choose the types of emails you receive.

Unsubscribe from all future emails (http://95135.hs-sites.com/hs/manage-preferences/unsubscribe-all?v=1&d=eyJlYSI6InJlcGx5KzAwYmY3MzRhN2YzN2UwMWI0MzBlMzZlZWFjZDNmY2E4NjEzN2IyNDNkZDc1MThiODkyY2YwMDAwMDAwMTEzMGE3Zjk0OTJhMTY5Y2UwNjZkMWM3ZUByZXBseS5naXRodWIuY29tIiwiZWMiOjI5MDgzNDQzLCJzdWJzY3JpcHRpb25JZCI6MjEwOTk5LCJldCI6MTQ2MjIwNzAxNjk0NSwiZXUiOiJjMzc5MWYxMC1kMWJlLTQ4NWYtOTFiOC1lNzZmMDRhODk1MTQifQ%3D%3D&utm_campaign=Feverbee+and+Vanilla&utm_source=hs_email&utm_medium=email&utm_content=29083443&_hsenc=p2ANqtz--tItkxQ-jsJcbxtQlbrJm5-MstP-15RfPCav92L6D5sH4DdPlCfcCvYcyexsgZIO01UGrtG3Z5J6zJ3_SAfL1o7sM275KzuIs6dUUGMrtwiL9436Sg0zRRjyt_eVmRePwaMMuplyfwF7MAAVmXlJNgI44b4NixJODS3Bx_6nOjVGNU7VPRCu82wZvLXWl1iPX5ruiZ0aKmKTkJej89XV3yWWNfqA&_hsmi=29083443)
